version: '3.7'

services:
  postgresql:
    container_name: restaurant-postgres
    image: postgres
    environment:
      - POSTGRES_DB=restaurant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - restaurant-network

networks:
  restaurant-network:
